# Aliases
alias g=git
alias glg="git log"
alias dc=docker-compose
alias go=richgo
alias gst="git status"
alias v="nvim"
#alias vi=vim
#alias vim=vim
#alias man="man -Hfirefox"
#alias open="gio open"
alias c=code
alias cm=chezmoi
alias cz=chezmoi
alias ce="chezmoi edit --watch $0"
alias kc=kubectl
alias tf=terraform
#alias docker=podman
alias rzi="rm -rf **/*Zone.Identifier"
alias py=python3
