k9s:
  refreshRate: 1
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: cluster-dev
  currentCluster: cluster-dev
  clusters:
    cluster:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - vpa
        - ingress-nginx
        - kube-system
        - sample
        - gatekeeper-system
        - clusterinfo
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    cluster-dev:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - argocd
        - kube-public
        - kube-node-lease
        - kube-system
        - gatekeeper-system
        - all
        - default
      view:
        active: nodes
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    mega-dmytro-kubernetes:
      namespace:
        active: platform
        lockFavorites: false
        favorites:
        - platform
        - argocd
        - upbound-system
        - all
        - external-secrets
        - default
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 95
      warn: 85
  screenDumpDir: /tmp/k9s-screens-clwaltke
