name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * 6"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: sudo apt-get install zsh
      - run: |
          mkdir -p ~/dotfiles-install-dir
      - run: |
          HOME=~/dotfiles-install-dir sh ./install
